server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:40019/ims_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

jwt:
  secret: jwtsecret
