import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <nav>
        <Link href='/login'>Login</Link>
        <Link href='/register'>Register</Link>
      </nav>

      <main>{children}</main>
    </>
  );
};

export default Layout;
